version: "3.9"

services:
  doom:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: doom-lab
    tty: true
    stdin_open: true
    network_mode: host
    cap_add:
        - NET_ADMIN

    volumes:
      - ./doom:/home/doom/volume
    restart: unless-stopped

